### ISSUE TITLE
GUI overlapping

### ISSUE THREAD

**Issue by COMBOhrenovke** [Fuzss/animatedrecipebutton#2]
When used with Curios API (Forge), and when its GUI is opened the recipe book is shown where the Curio GUI button should be.
This doesn't crash the game or cause any harm (you can still get out of Curio GUI), but should still be fixed as it doesn't look very pretty and is most probably not the intended behaviour.

Pretty simple issue. If you need pictures of the issue in game, I could send some here.

**Comment by Fuzss** [comment]
Can you post an image please?

**Comment by COMBOhrenovke** [comment]
![2021-03-01_16 39 09](https://user-images.githubusercontent.com/56222746/109520806-e7643600-7aac-11eb-98b0-5132c4f913ff.png)
![2021-03-01_16 39 14](https://user-images.githubusercontent.com/56222746/109520816-e92df980-7aac-11eb-949c-b48a045c7c0a.png)
![2021-03-01_16 39 16](https://user-images.githubusercontent.com/56222746/109520825-eaf7bd00-7aac-11eb-99a3-18e85b96ef3d.png)
Here they are! Sry it took me so long...

**Comment by COMBOhrenovke** [comment]
Same happens w only the Curios API and this mod. Also, the same happens in survival.

**Comment by Fuzss** [comment]
Fixed in v1.3.2.
